// <auto-generated />
namespace Imagine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingDuration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingDuration));
        
        string IMigrationMetadata.Id
        {
            get { return "201512071410007_AddingDuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
